name: Softcent
description: Softcent test app
publish_to: 'none'
ersion: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  http: ^0.13.4
  flutter_svg: ^1.1.0
  google_fonts: ^3.0.1
  expandable: ^5.0.1
  shimmer: ^2.0.0
  cached_network_image: ^3.2.1
  flutter_screenutil: ^5.5.3+2
  card_swiper: ^2.0.3
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
     - assets/
     - assets/icons/